gems: [jekyll-paginate]

markdown: rdiscount
highlither: true
safe: false


description: "Coding, startups and ideas."
logo: false
meta_description: "Rosario's Blog. Coding, startups and ideas."

paginate: 15
# Details for the RSS feed generator
name:           Rosario's Blog

# url:            'http://rosario.io'
url:            '/'
author:         'Rosario Rascuna'
rss_path: 		'/'