name: Jkmangang's Blog
description: Writing about music, thoughts and ideas.
meta_description: Jkmangang's Blog. Writing about music, technology and his biased-thoughts.
date: 2012
permalink: /:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
baseurl: /
domain_name: 'jkmangang.github'
google_analytics: 'UA-92510047-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            '/'
author:         'Jkmangang'
