name: Jkmangang's Blog
description: Music, technology and ideas.
meta_description: Jkmangang's Blog. Music, thoughts and ideas.
date: 2012
permalink: /:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
baseurl: /
domain_name: 'jkmangang.github.io'
google_analytics: 'UA-92510047-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            '/'
author:         'Jkmangang'
